### ISSUE TITLE
Ansibilize Avalon Solr Server

### ISSUE THREAD

**Issue by cachemeoutside** [UCLALibrary/avalon#20]
- [x] p-w-avalonsolr01 launched
- [x] Ansible playbook / roles created
- [x] http://p-w-avalonsolr01.library.ucla.edu/solr accessible to Avalon services

**Comment by santhoshdkucla** [comment]
Per Epic 4

**Comment by cachemeoutside** [comment]
Ansible roles and playbook used defined here:
https://github.com/UCLALibrary/ansible_uclalib_plays/blob/master/avalon/lib_solr.yml
